### PR TITLE
Fix webpack integration

### PR DESCRIPTION
**Pull request by ivawzh**
Try to make this package work better with Webpack, by sorting module dependencies and replacing node-fetch with isomorphic-fetch. 

Also aim to fix https://github.com/lynndylanhurley/redux-auth/issues/26

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
LGTM :+1:

Thanks @ivawzh!!

**Comment by lynndylanhurley** [comment]
Do you have an npm account? If so email me your username and I'll add you as a collaborator so you can push releases.

**Comment by ivawzh** [comment]
Sounds good 😀. My NPM account is ivawzh.

**Comment by prisonier** [comment]
Does this PR has been pushed to npm ? I still get the issue

**Comment by cascornelissen** [comment]
@prisonier, the latest version on NPM is `0.0.2` which was released on [Dec 14, 2015](https://github.com/lynndylanhurley/redux-auth/releases). This PR was merged 24 days ago, which was in February 2016 and therefore it's not on NPM yet.

**Comment by prisonier** [comment]
@cascornelissen thanks for your answer. Are you a contributor of this package ?

**Comment by cascornelissen** [comment]
@prisonier, I am not, just did some digging. If you do want these changes you can and the project is still under heavy development you can always `npm install github:lynndylanhurley/redux-auth#ca075c6` to get the changes up until the merge of this PR.

**Comment by prisonier** [comment]
@cascornelissen  Many thanks, I wasn't aware of this possibility ! I will try to do so and maybe I could use the package.

**Pull request merged**
