### PR TITLE
Migrate to react-router@2 and react-router-redux

### PR DESCRIPTION
**Pull request by themouette**
Also moves the redux/react related dependencies to devDependencies. Maybe peerDependencies would be better.

Tests are passing, sample seems to work, but I have no devise_token_auth server to test.

I'll check if I can do something with passport though.

This is not perfect, I wanted to be able to see how it worked, migrating was a nice way to do so.

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
Thanks @themouette - I'll review this ASAP!

**Comment by lynndylanhurley** [comment]
Thanks @themouette - I really appreciate your help :+1: 

I'll review ASAP!

**Comment by themouette** [comment]
rebased onto master.

**Comment by josmardias** [comment]
Can we merge it? :+1:

**Comment by lynndylanhurley** [comment]
I'll merge this weekend. Sorry for the delay!

**Comment by josmardias** [comment]
@themouette Can you please revert those indentation changes on the package.json?
Probably you are using "npm --save/--save-dev" that applies npm indentation defaults (and I support it as a good practice) but it makes the PR harder to reason about.

**Comment by josmardias** [comment]
@themouette Also, can you please explain those peerDependencies?

**Comment by josmardias** [comment]
@themouette for example, I know that the dummy project uses redux-thunk, but it's a required peerDependency for other projects?

**Comment by josmardias** [comment]
@themouette also, you missed the ```npm run release``` command to update generated files on the root of the project

**Comment by lynndylanhurley** [comment]
@themouette - Thanks for your help. I don't have much free time these days so I'm giving you commit access to this repo.

**Pull request merged**
